### ISSUE TITLE
A typo in an example from Theories/UnicodeStrings.smt2.

### ISSUE THREAD

**Issue by wingsyuyi-satori** [SMT-LIB/SMT-LIB-Public-docs#33]
I noticed a small typo in the example at line 453 of the Theories/UnicodeStrings.smt2 file. The example demonstrates how string literals are resolved when they include characters that do not form valid escape sequences.

At line 453, the example is written as:

`⟦""\u2CA""⟧ = 0x0005C ⟦""u2CXA""⟧           (not an escape sequence)`

It appears that this example may have been copied incorrectly from the next line. The correct version should likely be:

`⟦""\u2CA""⟧ = 0x0005C ⟦""u2CA""⟧           (not an escape sequence)`

Apologies for any disturbance caused by pointing out this small issue. I have deep respect for the work done on the SMT-LIB project and greatly appreciate the effort that has gone into making it such a valuable resource!

**Comment by fontainep** [comment]
Hi,

thanks a lot for your sharp eye and taking the time to report this typo!  In principle, this is now fixed on the main source: https://smt-lib.org/theories-UnicodeStrings.shtml .

Let us know if you point out any other typo or mistake!  Meanwhile I will close the issue (which can be reopen if it is not perfectly fixed).

All the best,

  Pascal (also for Cesare and Clark)
